# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---

version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          name: Install Javascript dependencies
          command: npm --prefix ./glean install
      - run:
          name: Run linter
          command: npm --prefix ./glean run lint
      # Disabled because of bug 1704794.
      # - run:
      #    name: Run circular dependencies checker
      #    command: npm --prefix ./glean run lint:circular-deps

  unit-tests:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          name: Install Firefox related dependencies
          command: |
            sudo add-apt-repository ppa:ubuntu-mozilla-daily/ppa
            sudo apt update
            sudo apt install firefox-trunk
      - run:
          name: Install Javascript dependencies
          command: npm --prefix ./glean install
      - run:
          name: Run unit tests
          command: export PATH=.:$PATH && npm --prefix ./glean run test

  samples-tests:
    docker:
      - image: cimg/python:3.8.8-node
    steps:
      - checkout
      - run:
          name: Install Javascript dependencies for Glean
          command: npm --prefix ./glean install
      - run:
          name: Build & link Glean.js to use it in the samples
          command: |
              npm --prefix ./glean run build:webext
              npm --prefix ./glean run build:cli
              npm --prefix ./glean link
      - run:
          name: Install Javascript dependencies for the JS sample
          command: |
              npm --prefix ./samples/web-extension/javascript install
              npm --prefix ./samples/web-extension/javascript link @mozilla/glean
      - run:
          name: Build the JS sample
          command: npm --prefix ./samples/web-extension/javascript run build
      - run:
          name: Run samples tests
          command: export PATH=.:$PATH && npm --prefix ./samples/web-extension/javascript run test

  check-size:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          name: Get and post build sizes to GitHub PR
          command: bin/build-size-check.sh

  check-qt-js:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Install Javascript dependencies and build Glean.js for Qt
          command: |
            # We are on the CircleCI python docker image, so let's install npm and node.
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.0/install.sh | bash
            export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install node
            npm --prefix ./glean install
            npm --prefix ./glean run build:qt
      - run:
          name: Verify no Javascript errors found in Qt
          command: bin/qt-js-check.sh

  publish:
    docker:
      - image: cimg/node:14.13.1
    steps:
      - checkout
      - run:
          name: Install Javascript dependencies
          command: npm --prefix ./glean install
      - run:
          name: NPM Authentication
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > glean/.npmrc
      - run:
          name: Publish to npm
          command: export PATH=.:$PATH && (cd glean && npm publish --access public)
      - run:
          name: Get ghr release tool
          command: |
            GHR=ghr_v0.13.0_linux_amd64
            GHR_SHA256=c428627270ae26e206cb526cb8c7bdfba475dd278f6691ddaf863355adadfa13
            curl -sfSL --retry 5 -O "https://github.com/tcnksm/ghr/releases/download/v0.13.0/${GHR}.tar.gz"
            echo "${GHR_SHA256} *${GHR}.tar.gz" | sha256sum -c -
            tar -xf "${GHR}.tar.gz"
            cp ./${GHR}/ghr ghr
      - run:
          name: Publish to Github
          command: |
            # Attach Qt build to release
            npm --prefix ./glean install
            npm --prefix ./glean run build:qt
            cp glean/dist/glean.js glean/dist/glean_js-${CIRCLE_TAG}-qt.js
            ./ghr -u mozilla -replace ${CIRCLE_TAG} glean/dist/glean_js-${CIRCLE_TAG}-qt.js

workflows:
  version: 2
  ci:
    jobs:
      - lint
      - unit-tests
      - check-qt-js
      - samples-tests
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      # Comment this job away until Bug 1681899 is resolved.
      # - check-size:
      #     filters:
      #       branches:
      #         ignore: main
